version: "3"
services:
  website:
    build: .
    environment:
      - MY_NAME=HAGAI
    depends_on:
      - mongodb
    ports:
      - "80:80"
    restart: always

  mongodb:
    hostname: db-movie
    image: mongo
    ports:
      - 8081:27017
    restart: always
