#! /bin/bash

# download docker
yum update
yum install docker -y

# 1. Get pip3
sudo yum install python3-pip

# 2. Then run any one of the following
sudo pip3 install docker-compose # with root access

systemctl enable docker.service
systemctl start docker.service

# curl/dowload the files from my github repo
yum install git
git clone

# insert the API KEY to the param store

# docker-compose up
# not working when I did sudo docker-compose up so:
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose